#!/bin/sh
# The first version of this script used a very linux-dependent aproach.
# Modified to use cdparanoia and check for audio files on the CD

#NOTE! Change the CDROM variable to point to your device.
CDROM=/dev/cdrom
DO_RIP="/home/arthur/programs/abcde/abcde-2.9/abcde -x -b -N"
CDPARANOIA="cdparanoia -Q 2>&1 | grep 'audio only'"

while true; do
#     CAPACITY=`cat $CDROM/capacity`
#     if [ $CAPACITY -gt 0 ]; then
#         $RIP
#     fi

	GO=$CDPARANOIA
	RET=$?
	if [ $RET = "0" ] ; then
		DO_RIP
	fi
done
