#!/bin/sh 
 
_FILE=$(readlink -f "$1") 
_DIR=$(dirname "$_FILE") 
_BASE="${_FILE%.*}" 
_PRFX="---COMPILE:" 
_ARGS="$(grep -oP -- "$_PRFX.*$" "$_FILE" |  sed -s "s|$_PRFX||")" 
 
cd "$_DIR" || return 
 
case "$_FILE" in 
*\.ms) groff -e -t -ms -U "$_FILE" -T pdf > "$_BASE.pdf"
    ;; 
esac 
